microservice-chart:
  namespace: "diego"

  deployment:
    create: true
    replicas: 1

  serviceAccount:
    name: diego-workload-identity

  envConfig:
    APP: basic
    MY_APP_COLOR: "green"

  envSecret:
    MY_KV_SECRET: dvopla-d-itn-dev-aks-apiserver-url
    TEST: test

  image:
    repository: ghcr.io/pagopa/devops-java-springboot-color
    tag: latest
    pullPolicy: Always

  tmpVolumeMount:
    create: true
    mounts:
      - name: tmp
        mountPath: /tmp
      - name: logs
        mountPath: /app/logs

  livenessProbe:
    httpGet:
      path: /status/live
      port: 8080
    initialDelaySeconds: 30
    failureThreshold: 6
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /status/ready
      port: 8080
    initialDelaySeconds: 30
    failureThreshold: 6
    periodSeconds: 10

  service:
    create: true
    type: ClusterIP
    ports:
      - 8080

  ingress:
    create: true
    host: diego.itn.internal.devopslab.pagopa.it
    path: /diego/one-color(/|$)(.*)
    rewriteTarget: /$2
    servicePort: 8080

  resources:
    requests:
      memory: "256Mi"
      cpu: "150m"
    limits:
      memory: "256Mi"
      cpu: "150m"

  keyvault:
    name: "dvopla-d-itn-diego-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  podDisruptionBudget:
    create: false
    minAvailable: 1

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.azure.com/mode
            operator: In
            values:
            - user
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              aadpodidbinding: diego-pod-identity
          namespaces: ["diego"]
          topologyKey: topology.kubernetes.io/zone
