#postman-test:
#  run: true
#  nameRepo: devops-java-springboot-color
#  dir: src/test/postman
#  collectionName: mil-papos.postman_collection.json
#  envVariables: dev.postman_environment.json

microservice-chart:
  namespace: "diego"

  deployment:
    create: true
    replicas: 1

  serviceAccount:
    name: diego-workload-identity

  envConfig:
    APP: basic
    MY_APP_COLOR: "green"

  envSecret:
    MY_KV_SECRET: dvopla-d-itn-dev-aks-apiserver-url
    TEST: test

  image:
    repository: ghcr.io/pagopa/devops-app-status
    tag: v2.1.0
    pullPolicy: Always

  autoscaling:
    enable: true
    minReplica: 0
    maxReplica: 3
    pollingInterval: 30 # seconds
    cooldownPeriod: 10 # seconds
    triggers:
      - type: cron
        metadata:
          # Required
          timezone: Europe/Rome  # The acceptable values would be a value from the IANA Time Zone Database.
          start: 0 19 * * *
          end: 40 19 * * *
          desiredReplicas: "5"
      - type: cpu
        metadata:
          type: Utilization
          value: "60"

  tmpVolumeMount:
    create: true
    mounts:
      - name: tmp
        mountPath: /tmp
      - name: logs
        mountPath: /app/logs

  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 3
    failureThreshold: 6
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 3
    failureThreshold: 6
    periodSeconds: 10

  service:
    create: true
    type: ClusterIP
    ports:
      - 8080

  ingress:
    create: true
    host: diego.itn.internal.devopslab.pagopa.it
    path: /diego/status-01(/|$)(.*)
    rewriteTarget: /$2
    servicePort: 8080

  resources:
    requests:
      memory: "10Mi"
      cpu: "10m"
    limits:
      memory: "10Mi"
      cpu: "10m"

  keyvault:
    name: "dvopla-d-itn-diego-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  podDisruptionBudget:
    create: false
    minAvailable: 1

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: In
                values:
                  - user
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                aadpodidbinding: diego-pod-identity
            namespaces: ["diego"]
            topologyKey: topology.kubernetes.io/zone
